In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv(r"Downloads\amazon_books_Data.csv")
df

Unnamed: 0 market_place customer_id         review_id    product_id  \
0            0         "US"  "25933450"   "RJOVP071AVAJO"  "0439873800"   
1            1         "US"   "1801372"  "R1ORGBETCDW3AI"  "1623953553"   
2            2         "US"   "5782091"   "R7TNRFQAOUTX5"  "142151981X"   
3            3         "US"  "32715830"  "R2GANXKDIFZ6OI"  "014241543X"   
4            4         "US"  "14005703"  "R2NYB6C3R8LVN6"  "1604600527"   
..         ...          ...         ...               ...           ...   
95          95         "US"   "9373014"   "RVAXL2PDUOYF3"  "1781716498"   
96          96         "US"  "31654227"  "R2U47B96XHOLYN"  "0062091158"   
97          97         "US"  "12103883"  "R2N3K8FK4UI2IO"  "1509203141"   
98          98         "US"  "45587944"  "R34OETSC748FNA"  "0689120079"   
99          99         "US"  "38753491"  "R3DP1CYB1M7V26"  "0990454665"   

   product_parent                                      product_title  \
0      "84656342"     "There Was an Old Lady Who Swallowed a Shell!"   
1     "729938122"                                   "I Saw a Friend"   
2     "678139048"                             "Black Lagoon, Vol. 6"   
3     "712432151"                                        "If I Stay"   
4     "800572372"                          "Stars 'N Strips Forever"   
..            ...                                                ...   
95    "307416668"  "Fairytales Gone Wrong: Give Us a Smile Cinder...   
96    "178935212"                                  "King (Prophecy)"   
97    "803771611"                                     "Return to Me"   
98    "133206690"  "Fatal Voyage: The Sinking of the Uss Indianap...   
99    "865890307"  "The Gender of Inanimate Objects and Other Sto...   

   product_category  star_rating  helpful_votes  total_votes     vine  \
0           "Books"            1              0            0  0 \t(N)   
1           "Books"            1              0            0  0 \t(N)   
2           "Books"            1              0            0  0 \t(N)   
3           "Books"            1              0            0  0 \t(N)   
4           "Books"            1              2            2  0 \t(N)   
..              ...          ...            ...          ...      ...   
95          "Books"            1              0            0  0 \t(N)   
96          "Books"            0              0            0  0 \t(N)   
97          "Books"            1              3            3  0 \t(N)   
98          "Books"            1              0            0  0 \t(N)   
99          "Books"            1              1            1  0 \t(N)   

   verified_purchase                                    review_headline  \
0            1 \t(Y)                                       "Five Stars"   
1            1 \t(Y)  "Please buy "I Saw a Friend"! Your children wi...   
2            1 \t(Y)                                    "Shipped fast."   
3            0 \t(N)                                       "Five Stars"   
4            1 \t(Y)                                       "Five Stars"   
..               ...                                                ...   
95           1 \t(Y)  "We always talk about hygiene here and this re...   
96           0 \t(N)  "King (The Dragon King Chronicles, #3) by Elle...   
97           0 \t(N)  "and their hearts loved deeply while continuou...   
98           1 \t(Y)  "Story that has been too long covered up. Show...   
99           1 \t(Y)                                "I loved this book"   

                                          review_body review_date  \
0                "I love it and so does my students!"  2015-08-31   
1   "My wife and I ordered 2 books and gave them a...  2015-08-31   
2   "Great book just like all the others in the se...  2015-08-31   
3                                      "So beautiful"  2015-08-31   
4   "Enjoyed the author's story and his quilts are...  2015-08-31   
..                                            

In [3]:
data=df.iloc[:,[-6,-4]]

In [4]:
data

review_body Sentiment_books
0                "I love it and so does my students!"        positive
1   "My wife and I ordered 2 books and gave them a...        positive
2   "Great book just like all the others in the se...        positive
3                                      "So beautiful"        positive
4   "Enjoyed the author's story and his quilts are...        positive
..                                                ...             ...
95  "We always talk about hygiene here and this re...        positive
96  "(Source: I received a digital copy of this bo...        negaitve
97  "You'll find yourself transported back to war-...        positive
98  "Story that has been too long covered up. Show...        positive
99  "I loved this book!<br /><br />Maya is such an...        positive

[100 rows x 2 columns]

In [5]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
data.iloc[:,-1]=label.fit_transform(data.iloc[:,-1])

In [6]:
data

review_body  Sentiment_books
0                "I love it and so does my students!"                1
1   "My wife and I ordered 2 books and gave them a...                1
2   "Great book just like all the others in the se...                1
3                                      "So beautiful"                1
4   "Enjoyed the author's story and his quilts are...                1
..                                                ...              ...
95  "We always talk about hygiene here and this re...                1
96  "(Source: I received a digital copy of this bo...                0
97  "You'll find yourself transported back to war-...                1
98  "Story that has been too long covered up. Show...                1
99  "I loved this book!<br /><br />Maya is such an...                1

[100 rows x 2 columns]

In [7]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [8]:
corpus=[]
for i in range(0,100):
    reviews=re.sub("[^A-Za-z]",' ',data['review_body'][i])
    reviews=reviews.lower()
    reviews=reviews.split()
    pst=PorterStemmer()
    reviews=[pst.stem(word)for word in reviews if word not in set(stopwords.words("english"))]
    reviews=''.join(reviews)
    corpus.append(reviews)

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
X=tf.fit_transform(corpus).toarray()
y=data.iloc[:,-1].values

In [10]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
y

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1])

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [13]:
from sklearn.naive_bayes import BernoulliNB
ber=BernoulliNB()
ber.fit(X_train,y_train)
y_pred=ber.predict(X_train)

In [14]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

0.825

In [15]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[ 0, 14],
       [ 0, 66]], dtype=int64)

In [16]:
from sklearn.metrics import classification_report
report=classification_report(y_train,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00        14\n           1       0.82      1.00      0.90        66\n\n    accuracy                           0.82        80\n   macro avg       0.41      0.50      0.45        80\nweighted avg       0.68      0.82      0.75        80\n'

In [17]:
from sklearn.svm import SVC
svc=SVC(C= 0.1, gamma= 'auto', kernel='rbf')
svc.fit(X_train,y_train)
y_pred=svc.predict(X_train)

In [18]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

0.825

In [19]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[ 0, 14],
       [ 0, 66]], dtype=int64)

In [20]:
from sklearn.metrics import classification_report
report=classification_report(y_train,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00        14\n           1       0.82      1.00      0.90        66\n\n    accuracy                           0.82        80\n   macro avg       0.41      0.50      0.45        80\nweighted avg       0.68      0.82      0.75        80\n'

In [21]:
from sklearn.model_selection import GridSearchCV
params={"C":[0.1,0.001],"kernel":["rbf","linear"],"gamma":["auto","scale"]}
grid=GridSearchCV(estimator=svc,param_grid=params,cv=5)
grid.fit(X_train,y_train)
print("best params:",grid.best_params_)
print("best score:",grid.best_score_)

best params: {'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'}
best score: 0.825


In [22]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
y_pred=knn.predict(X_train)

In [23]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

0.825

In [24]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[ 0, 14],
       [ 0, 66]], dtype=int64)

In [25]:
from sklearn.metrics import classification_report
report=classification_report(y_train,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00        14\n           1       0.82      1.00      0.90        66\n\n    accuracy                           0.82        80\n   macro avg       0.41      0.50      0.45        80\nweighted avg       0.68      0.82      0.75        80\n'

In [26]:
from sklearn.model_selection import GridSearchCV
params={"n_neighbors":[5,7,10],"weights":["uniform","distance"]}
grid=GridSearchCV(estimator=knn,param_grid=params,cv=5)
grid.fit(X_train,y_train)
print("best_score:",grid.best_score_)
print("best_params:",grid.best_params_)

best_score: 0.825
best_params: {'n_neighbors': 5, 'weights': 'uniform'}


In [27]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(X_train,y_train)
y_pred=dtree.predict(X_train)

In [28]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

1.0

In [29]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[14,  0],
       [ 0, 66]], dtype=int64)

In [30]:
from sklearn.metrics import classification_report
report=classification_report(y_train,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        14\n           1       1.00      1.00      1.00        66\n\n    accuracy                           1.00        80\n   macro avg       1.00      1.00      1.00        80\nweighted avg       1.00      1.00      1.00        80\n'

In [31]:
from sklearn.model_selection import RandomizedSearchCV
params={'criterion': ['gini', 'entropy'],
    'max_depth':[1,3,5,7,10],
    'min_samples_split':[2,5,6,10,15, 20],
    'min_samples_leaf':[2,5,6,10]}
random=RandomizedSearchCV(estimator=dtree,param_distributions=params,cv=5)
random.fit(X_train,y_train)
print("best_score:",random.best_score_)
print("best_params:",random.best_params_)

best_score: 0.825
best_params: {'min_samples_split': 2, 'min_samples_leaf': 5, 'max_depth': 3, 'criterion': 'entropy'}


In [32]:
from sklearn.ensemble import RandomForestClassifier
rndf=RandomForestClassifier()
rndf.fit(X_train,y_train)
y_pred=rndf.predict(X_train)

In [33]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

1.0

In [34]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[14,  0],
       [ 0, 66]], dtype=int64)

In [35]:
from sklearn.metrics import classification_report
report=classification_report(y_train,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        14\n           1       1.00      1.00      1.00        66\n\n    accuracy                           1.00        80\n   macro avg       1.00      1.00      1.00        80\nweighted avg       1.00      1.00      1.00        80\n'

In [36]:
from sklearn.model_selection import RandomizedSearchCV
params={'n_estimators':[100, 1000],
    'criterion': ['gini', 'entropy'],
    'max_depth':[1,3,5,7,10],
    'min_samples_split':[2,5,6,10,15, 20],
    'min_samples_leaf':[2,5,6,10]}
random=RandomizedSearchCV(estimator=rndf,param_distributions=params,cv=5)
random.fit(X_train,y_train)
print("best_score:",random.best_score_)
print("best_params:",random.best_params_)

best_score: 0.825
best_params: {'n_estimators': 100, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_depth': 1, 'criterion': 'entropy'}


In [37]:
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(X_train,y_train)
y_pred=xgb.predict(X_train)

In [38]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

0.825

In [39]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[ 0, 14],
       [ 0, 66]], dtype=int64)

In [40]:
from sklearn.metrics import classification_report
report=classification_report(y_train,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00        14\n           1       0.82      1.00      0.90        66\n\n    accuracy                           0.82        80\n   macro avg       0.41      0.50      0.45        80\nweighted avg       0.68      0.82      0.75        80\n'

Amazon Grocery DataSet

In [41]:
data2=pd.read_csv(r"Downloads\amazon_grocery_Data.csv")
data2

Unnamed: 0 market_place customer_id         review_id    product_id  \
0            0         "US"  "42521656"  "R26MV8D0KG6QI6"  "B000SAQCWC"   
1            1         "US"  "12049833"  "R1OF8GP57AQ1A0"  "B00509LVIQ"   
2            2         "US"    "107642"  "R3VDC1QB6MC4ZZ"  "B00KHXESLC"   
3            3         "US"   "6042304"  "R12FA3DCF8F9ER"  "B000F8JIIC"   
4            4         "US"  "18123821"   "RTWHVNV6X4CNJ"  "B004ZWR9RQ"   
..         ...          ...         ...               ...           ...   
95          95         "US"  "41855640"  "R14RNK4F6OPVHI"  "B00MGDVYCM"   
96          96         "US"  "13730310"  "R29XUIKKYB1SVA"  "B00NESWWIS"   
97          97         "US"  "48872127"  "R22YPES48XVR9Z"  "B00O8SQTIM"   
98          98         "US"  "12859252"   "RTL7D7ONFKQTO"  "B0064OLVFY"   
99          99         "US"  "33828780"  "R2B9WKQP7ZZVPQ"  "B006ONNLNA"   

   product_parent                                      product_title  \
0     "159713740"  "The Cravings Place Chocolate Chunk Cookie Mix...   
1     "138680402"          "Mauna Loa Macadamias, 11 Ounce Packages"   
2     "252021703"  "Organic Matcha Green Tea Powder - 100% Pure M...   
3     "752728342"  "15oz Raspberry Lyons Designer Dessert Syrup S...   
4     "552138758"  "Stride Spark Kinetic Fruit Sugar Free Gum, 14...   
..            ...                                                ...   
95    "527526119"  "Emerald Cocoa Roast Dark Chocolate Almonds - ...   
96    "807933739"  "Fiber One Chewy Bars Oats & Chocolate: 36 Bar...   
97     "46432804"      "Gerber Good Start Infant Formula Sample Box"   
98    "518513658"                            "Cheese Wax 1 lb - Red"   
99    "702537450"  "Gustaf’s Traditional Dutch Authentic Double S...   

   product_category  star_rating  helpful_votes  total_votes     vine  \
0         "Grocery"            1              0            0  0 \t(N)   
1         "Grocery"            1              0            0  0 \t(N)   
2         "Grocery"            1              0            0  0 \t(N)   
3         "Grocery"            1              0            0  0 \t(N)   
4         "Grocery"            1              0            0  0 \t(N)   
..              ...          ...            ...          ...      ...   
95        "Grocery"            1              0            0  0 \t(N)   
96        "Grocery"            1              2            3  0 \t(N)   
97        "Grocery"            0              0            0  0 \t(N)   
98        "Grocery"            1              0            0  0 \t(N)   
99        "Grocery"            0              0            5  0 \t(N)   

   verified_purchase                       review_headline  \
0            1 \t(Y)  "Using these for years - love them."   
1            1 \t(Y)                           "Wonderful"   
2            0 \t(N)                          "Five Stars"   
3            1 \t(Y)                          "Five Stars"   
4            1 \t(Y)                          "Five Stars"   
..               ...                                   ...   
95           1 \t(Y)                          "Five Stars"   
96           0 \t(N)                   "Very Satisfying!!"   
97           0 \t(N)                        "Okay formula"   
98           1 \t(Y)                          "Five Stars"   
99           1 \t(Y)            "It's actually TOO salty."   

                                          review_body review_date  \
0   "As a family allergic to wheat, dairy, eggs, n...  2015-08-31   
1   "My favorite nut. Creamy, crunchy, salty, and ...  2015-08-31   
2   "This green tea tastes so good! My girlfriend ...  2015-08-31   
3   "I love Melissa's brand but this is a great se...  2015-08-31   
4                                              "good"  2015-08-31   
..                                                ...         ...   
95                                        "Delicious"  2015-08-31   
96  "I needed more fiber in my diet and decided to...  2015-08-3

In [42]:
df2=data2.iloc[:,[-3,-1]]
df2

review_body Sentiment_grcry
0   "As a family allergic to wheat, dairy, eggs, n...        positive
1   "My favorite nut. Creamy, crunchy, salty, and ...        positive
2   "This green tea tastes so good! My girlfriend ...        positive
3   "I love Melissa's brand but this is a great se...        positive
4                                              "good"        positive
..                                                ...             ...
95                                        "Delicious"        positive
96  "I needed more fiber in my diet and decided to...        positive
97  "Like most working moms, I can't pump enough t...        negaitve
98                                         "Love it!"        positive
99     "Not what I expected. Did not like it at all."        negaitve

[100 rows x 2 columns]

In [43]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df2.iloc[:,-1]=label.fit_transform(df2.iloc[:,-1])

In [44]:
df2

review_body  Sentiment_grcry
0   "As a family allergic to wheat, dairy, eggs, n...                1
1   "My favorite nut. Creamy, crunchy, salty, and ...                1
2   "This green tea tastes so good! My girlfriend ...                1
3   "I love Melissa's brand but this is a great se...                1
4                                              "good"                1
..                                                ...              ...
95                                        "Delicious"                1
96  "I needed more fiber in my diet and decided to...                1
97  "Like most working moms, I can't pump enough t...                0
98                                         "Love it!"                1
99     "Not what I expected. Did not like it at all."                0

[100 rows x 2 columns]

In [45]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [46]:
corpus2=[]
for i in range(0,100):
    reviews=re.sub("^A-Za-z",' ',df2['review_body'][i])
    reviews=reviews.lower()
    reviews=reviews.split()
    pst=PorterStemmer()
    reviews=[pst.stem(word)for word in reviews if word not in set(stopwords.words("english"))]
    reviews=' '.join(reviews)
    corpus2.append(reviews)

In [47]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(corpus2).toarray()
y=df2.iloc[:,-1].values

In [48]:
from sklearn.naive_bayes import BernoulliNB
ber=BernoulliNB()
ber.fit(X_train,y_train)
y_pred=ber.predict(X_train)

In [49]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

0.825

In [50]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[ 0, 14],
       [ 0, 66]], dtype=int64)

In [51]:
from sklearn.metrics import classification_report
report=classification_report(y_train,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00        14\n           1       0.82      1.00      0.90        66\n\n    accuracy                           0.82        80\n   macro avg       0.41      0.50      0.45        80\nweighted avg       0.68      0.82      0.75        80\n'

In [52]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(X_train,y_train)
y_pred=svc.predict(X_train)

In [53]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

1.0

In [54]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[14,  0],
       [ 0, 66]], dtype=int64)

In [55]:
from sklearn.metrics import classification_report
report=classification_report(y_train,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        14\n           1       1.00      1.00      1.00        66\n\n    accuracy                           1.00        80\n   macro avg       1.00      1.00      1.00        80\nweighted avg       1.00      1.00      1.00        80\n'

In [56]:
from sklearn.model_selection import GridSearchCV
params={"C":[0.1,0.001],"kernel":["rbf","linear"],"gamma":["auto","scale"]}
grid=GridSearchCV(estimator=svc,param_grid=params,cv=5)
grid.fit(X_train,y_train)
print("best params:",grid.best_params_)
print("best score:",grid.best_score_)

best params: {'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'}
best score: 0.825


In [57]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
y_pred=knn.predict(X_train)

In [58]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

0.825

In [59]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[ 0, 14],
       [ 0, 66]], dtype=int64)

In [60]:
from sklearn.model_selection import GridSearchCV
params={"n_neighbors":[5,7,10],"weights":["uniform","distance"]}
grid=GridSearchCV(estimator=knn,param_grid=params,cv=5)
grid.fit(X_train,y_train)
print("best_score:",grid.best_score_)
print("best_params:",grid.best_params_)

best_score: 0.825
best_params: {'n_neighbors': 5, 'weights': 'uniform'}


In [61]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()
tree.fit(X_train,y_train)
y_pred=tree.predict(X_train)

In [62]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

1.0

In [63]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[14,  0],
       [ 0, 66]], dtype=int64)

In [64]:
from sklearn.metrics import classification_report
report=classification_report(y_train,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        14\n           1       1.00      1.00      1.00        66\n\n    accuracy                           1.00        80\n   macro avg       1.00      1.00      1.00        80\nweighted avg       1.00      1.00      1.00        80\n'

In [65]:
from sklearn.model_selection import RandomizedSearchCV
params={'criterion': ['gini', 'entropy'],
    'max_depth':[1,3,5,7,10],
    'min_samples_split':[2,5,6,10,15, 20],
    'min_samples_leaf':[2,5,6,10]}
random=RandomizedSearchCV(estimator=dtree,param_distributions=params,cv=5)
random.fit(X_train,y_train)
print("best_score:",random.best_score_)
print("best_params:",random.best_params_)

best_score: 0.825
best_params: {'min_samples_split': 6, 'min_samples_leaf': 10, 'max_depth': 7, 'criterion': 'gini'}


In [66]:
from sklearn.ensemble import RandomForestClassifier
rndf=RandomForestClassifier()
rndf.fit(X_train,y_train)
y_pred=rndf.predict(X_train)

In [67]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

1.0

In [68]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[14,  0],
       [ 0, 66]], dtype=int64)

In [69]:
from sklearn.metrics import classification_report
report=classification_report(y_train,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        14\n           1       1.00      1.00      1.00        66\n\n    accuracy                           1.00        80\n   macro avg       1.00      1.00      1.00        80\nweighted avg       1.00      1.00      1.00        80\n'

In [70]:
from sklearn.model_selection import RandomizedSearchCV
params={'n_estimators':[100, 1000],
    'criterion': ['gini', 'entropy'],
    'max_depth':[1,3,5,7,10],
    'min_samples_split':[2,5,6,10,15, 20],
    'min_samples_leaf':[2,5,6,10]}
random=RandomizedSearchCV(estimator=rndf,param_distributions=params,cv=5)
random.fit(X_train,y_train)
print("best_score:",random.best_score_)
print("best_params:",random.best_params_)

best_score: 0.825
best_params: {'n_estimators': 1000, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_depth': 3, 'criterion': 'gini'}


In [71]:
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(X_train,y_train)
y_pred=xgb.predict(X_train)

In [72]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_train,y_pred)
acc

0.825

In [73]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train,y_pred)
cm

array([[ 0, 14],
       [ 0, 66]], dtype=int64)

In [74]:
from sklearn.metrics import classification_report
report=classification_report(y_train,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00        14\n           1       0.82      1.00      0.90        66\n\n    accuracy                           0.82        80\n   macro avg       0.41      0.50      0.45        80\nweighted avg       0.68      0.82      0.75        80\n'